#!/usr/bin/env python3
from __future__ import annotations

import argparse
from concurrent.futures import ThreadPoolExecutor, as_completed
import json
import os
import re
import subprocess
import sys
import urllib.error
import urllib.parse
import urllib.request
from pathlib import Path
from typing import Any

try:
    import tiktoken  # type: ignore
except ImportError:  # The Harbor base image may not bundle the optional tokenizer.
    tiktoken = None

if tiktoken is not None:
    try:
        TOKEN_ENCODER = tiktoken.encoding_for_model(
            os.environ.get("PAPERBENCH_JUDGE_MODEL", "glm-5-3")
        )
    except KeyError:
        TOKEN_ENCODER = tiktoken.get_encoding("o200k_base")
else:
    TOKEN_ENCODER = None


# These are copied from the official PaperBench SimpleJudge whitelist. Code
# Development sees documentation, source, and configuration files. The list is
# applied after enumerating Git HEAD, so ignored/untracked data never enters the
# judge's file tree.
OFFICIAL_DOC_SUFFIXES = {".md", ".txt", ".rst"}
OFFICIAL_CODE_SUFFIXES = {
    ".py", ".R", ".Rmd", ".m", ".jl",
    ".c", ".h", ".cpp", ".hpp", ".cc", ".cxx", ".hxx",
    ".java", ".js", ".ts", ".scala", ".go", ".rs", ".sh",
    ".config", ".cfg", ".json", ".yaml", ".yml", ".toml", ".ini",
}
OFFICIAL_TABLE_SUFFIXES = {
    ".csv", ".tsv", ".psv", ".json", ".jsonl", ".html", ".xml",
    ".yaml", ".yml", ".toml", ".arff", ".tex", ".svm", ".libsvm",
}
OFFICIAL_BLACKLISTED_DIRS = {
    "venv", ".venv", ".env", "wandb", ".egg-info", ".git", ".github",
    "__pycache__", "node_modules",
}
OFFICIAL_FILE_READ_LIMIT = 200_000
OFFICIAL_CONTEXT_BUFFER_TOKENS = 10_000
OFFICIAL_RELEVANT_FILES_BUFFER_TOKENS = 2_000

OFFICIAL_FILE_RANKING_PROMPT = """You are judging an attempt to reproduce a research paper. You will be shown a paper, a resolution criteria, and a set of files.
The resolution criteria is a specific aspect of the paper that you are marking. The set of files is the submission that someone has made, that is attempting to reproduce the paper.
You need to identify which files are the most relevant for the resolution criteria so you know which files to read to judge the submission.
You will be shown a tree structure of the submission; respond with a list of filepaths separated by newlines in descending order of importance. Each line should be a full filepath.
List all the files that are shown to you, do not leave any out. Do not return anything else."""
TASK_CATEGORY_QUESTIONS = {
    "Code Development": (
        "Does the code in the submission contain a correct implementation of this?"
        " Note: mere instructions or descriptions of implementations are not sufficient;"
        " you should check whether there is actual code that implements the requirement."
    ),
    "Code Execution": "Does running the reproduce.sh script lead to this being successfully executed?",
    "Result Analysis": "Did the reproduce.sh script execution produce evidence that agrees with these results?",
    "Subtree": "What is the weighted score of all the criteria in the subtree?",
}


class JudgeResponseParseError(ValueError):
    """The upstream answered, but its response did not satisfy the parser contract."""


def build_judge_task_prompt(code_only: bool) -> str:
    prompt = """You are judging a candidate's attempt to reproduce a research paper.

You will first be given the research paper, which you should read carefully and refer to as the ground truth for what constitutes a correct implementation and reproduction.

Following that, you will be presented with the candidate's submission: a set of files that attempts
to reproduce the paper."""
    if not code_only:
        prompt += """ The candidate has been asked to include a `reproduce.sh` script that, when executed, should run the full reproduction process and generate all results in the paper. If the script exists, we have already run it and included any output logs in the file `reproduce.log`. Any other files generated by the script may also be present, such as results, plots, or artifacts. If either `reproduce.sh` or `reproduce.log` is missing, you should consider any criteria relying on it to have failed."""
    prompt += "\n\nTo judge the submission, we have prepared a full rubric describing fine-grained criteria for different aspects of the paper."
    prompt += "\n\nYour task is to check the submission and its outputs for ONE specific criterion from this rubric."
    return prompt


OFFICIAL_GRADING_PROMPT = """You will now evaluate the submission above for the given criterion.

Please present your answer in 3 parts as follows:

# Expectations
Read the paper carefully to identify the parts relevant to your criterion. Describe what you expect correct resolution to look like, and what you will specifically look for in the submission.

# Reality
Explore the files provided for the submission along with the output logs to identify the parts that are relevant to the resolution criteria. When you have identified the relevant parts, comment on how they compare to your expectations above, and whether the attempt meets the resolution criteria. Be sure to describe only what has been given to you in the submission, and be explicit about which files you are referring to when you discuss them.

# Score
Reason about whether the criteria has been met. Give a score of either 0 or 1 depending on whether the criteria has been met, and explain why.

Other notes:
- You must always provide a score. If you have any uncertainties, make them clear in your discussion.
- All the files and logs from the submission attempt have been provided to you. If anything appears to be missing, assume that the attempt failed to produce it (treat it as a failure).
- Be strict and thorough in grading your resolution criteria, but do not check for things that are outside of your scope."""


def read_json(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8"))


def write_json(path: Path, payload: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def env_value(*names: str) -> str:
    for name in names:
        value = os.environ.get(name, "")
        if value and not value.strip().startswith("${"):
            return value
    return ""


def clipped(value: Any) -> float:
    try:
        return max(0.0, min(1.0, float(value)))
    except (TypeError, ValueError):
        return 0.0


def numeric_reward(
    *,
    score: float,
    format_score: float,
    submission_present: float,
    judge_available: float,
    llm_parse_ok: float,
    leaf_count: int,
    invalid_leaf_count: int,
    rubric_weight_total: float,
    reproduction_ran: float,
    reproduction_success: float,
    code_only: bool,
) -> dict[str, float]:
    score = clipped(score)
    return {
        "score": score,
        "weighted_score": score,
        "reward": score,
        "paperbench_score": score,
        "format": clipped(format_score),
        "submission_present": clipped(submission_present),
        "judge_available": clipped(judge_available),
        "llm_parse_ok": clipped(llm_parse_ok),
        "leaf_count": float(leaf_count),
        "invalid_leaf_count": float(invalid_leaf_count),
        "rubric_weight_total": float(rubric_weight_total),
        "reproduction_ran": clipped(reproduction_ran),
        "reproduction_success": clipped(reproduction_success),
        "code_only": 1.0 if code_only else 0.0,
    }


def rubric_leaves(node: Any) -> list[dict[str, Any]]:
    if not isinstance(node, dict):
        return []
    children = node.get("sub_tasks") if isinstance(node.get("sub_tasks"), list) else []
    if not children:
        return [node]
    out: list[dict[str, Any]] = []
    for child in children:
        out.extend(rubric_leaves(child))
    return out


def filtered_leaves(rubric: Any, *, code_only: bool) -> list[dict[str, Any]]:
    leaves = [leaf for leaf in rubric_leaves(rubric) if isinstance(leaf, dict)]
    if not code_only:
        return leaves
    code_leaves = [leaf for leaf in leaves if leaf.get("task_category") == "Code Development"]
    return code_leaves


def rubric_leaf_contexts(
    node: Any,
    prior_nodes: tuple[dict[str, Any], ...] = (),
) -> list[tuple[dict[str, Any], list[str]]]:
    """Port TaskNode.get_prior_nodes() for every leaf in depth-first order."""
    if not isinstance(node, dict):
        return []
    children = node.get("sub_tasks") if isinstance(node.get("sub_tasks"), list) else []
    if not children:
        requirements = [
            str(prior.get("requirements") or "")
            for prior in prior_nodes
            if str(prior.get("requirements") or "").strip()
        ]
        return [(node, requirements)]
    out: list[tuple[dict[str, Any], list[str]]] = []
    preceding_siblings: list[dict[str, Any]] = []
    for child in children:
        if not isinstance(child, dict):
            continue
        child_prior = prior_nodes + (node, *preceding_siblings)
        out.extend(rubric_leaf_contexts(child, child_prior))
        preceding_siblings.append(child)
    return out


def filtered_leaf_contexts(
    rubric: Any,
    *,
    code_only: bool,
    max_prior_nodes: int | None = None,
) -> list[tuple[dict[str, Any], list[str]]]:
    contexts = rubric_leaf_contexts(rubric)
    if code_only:
        contexts = [
            (leaf, ancestors)
            for leaf, ancestors in contexts
            if leaf.get("task_category") == "Code Development"
        ]
    if max_prior_nodes is not None:
        contexts = [
            (leaf, ancestors[-max_prior_nodes:])
            for leaf, ancestors in contexts
        ]
    return contexts


def weight_of(leaf: dict[str, Any]) -> float:
    try:
        return max(0.0, float(leaf.get("weight", 0.0)))
    except (TypeError, ValueError):
        return 0.0


def score_rubric_tree(
    node: Any,
    scores: dict[str, float],
    *,
    code_only: bool,
) -> float | None:
    """Aggregate scores exactly as PaperBench does: bottom-up at every branch.

    Rubric weights are local sibling weights, not globally comparable leaf
    weights.  In code-only mode, non-code leaves are pruned before each
    remaining sibling group is normalized.
    """
    if not isinstance(node, dict):
        return None
    children = node.get("sub_tasks") if isinstance(node.get("sub_tasks"), list) else []
    if not children:
        if code_only and node.get("task_category") != "Code Development":
            return None
        return scores.get(str(node.get("id") or ""), 0.0)

    graded_children: list[tuple[float, float]] = []
    for child in children:
        child_score = score_rubric_tree(child, scores, code_only=code_only)
        if child_score is not None and isinstance(child, dict):
            graded_children.append((weight_of(child), child_score))
    if not graded_children:
        return None
    total_weight = sum(weight for weight, _ in graded_children)
    if total_weight <= 0:
        return 0.0
    return sum(weight * score for weight, score in graded_children) / total_weight


def read_text(path: Path) -> str:
    if not path.is_file():
        return ""
    return path.read_text(encoding="utf-8", errors="replace")


def touched_since_reproduction_start(path: Path, reproduction_started_at: float | None) -> bool:
    if reproduction_started_at is None:
        return False
    try:
        return path.stat().st_mtime >= reproduction_started_at
    except OSError:
        return False


def collect_submission(
    root: Path,
    *,
    committed_only: bool,
    reproduction_started_at: float | None = None,
) -> dict[str, Any]:
    if not root.is_dir():
        return {"exists": False, "root": str(root), "files": [], "committed_only": committed_only}
    if committed_only:
        result = subprocess.run(
            ["git", "-C", str(root), "ls-tree", "-rlz", "--full-tree", "HEAD"],
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            check=False,
        )
        if result.returncode != 0:
            error = result.stderr.decode("utf-8", errors="replace")
            raise RuntimeError(f"cannot enumerate Git HEAD: {error[:1000]}")
        files: list[dict[str, Any]] = []
        for record in result.stdout.split(b"\0"):
            if not record or b"\t" not in record:
                continue
            header, raw_path = record.split(b"\t", 1)
            fields = header.split()
            if len(fields) < 4 or fields[1] != b"blob":
                continue
            relative = raw_path.decode("utf-8", errors="surrogateescape")
            path = Path(relative)
            if path.is_absolute() or ".." in path.parts:
                continue
            try:
                size = int(fields[3])
            except ValueError:
                continue
            files.append(
                {
                    "path": relative,
                    "bytes": size,
                    "mode": fields[0].decode("ascii", errors="replace"),
                    "oid": fields[2].decode("ascii", errors="replace"),
                    "committed": True,
                }
            )
    else:
        files = []
        for path in root.rglob("*"):
            if not path.is_file():
                continue
            try:
                size = path.stat().st_size
            except OSError:
                continue
            files.append(
                {
                    "path": path.relative_to(root).as_posix(),
                    "bytes": size,
                    "touched_by_reproduction": touched_since_reproduction_start(
                        path, reproduction_started_at
                    ),
                    "committed": False,
                }
            )
    files.sort(key=lambda row: str(row["path"]).lower())
    return {
        "exists": True,
        "root": str(root),
        "files": files,
        "file_count": len(files),
        "committed_only": committed_only,
    }


def whitelisted_submission_files(
    snapshot: dict[str, Any], task_category: str
) -> list[dict[str, Any]]:
    if task_category == "Result Analysis":
        allowed = OFFICIAL_DOC_SUFFIXES | OFFICIAL_TABLE_SUFFIXES
    elif task_category == "Subtree":
        allowed = OFFICIAL_DOC_SUFFIXES | OFFICIAL_CODE_SUFFIXES | OFFICIAL_TABLE_SUFFIXES
    else:
        allowed = OFFICIAL_DOC_SUFFIXES | OFFICIAL_CODE_SUFFIXES
    selected = []
    for row in snapshot.get("files", []):
        if not isinstance(row, dict):
            continue
        relative = Path(str(row.get("path") or ""))
        if relative.suffix not in allowed:
            continue
        if any(
            blacklisted in part
            for blacklisted in OFFICIAL_BLACKLISTED_DIRS
            for part in relative.parts
        ):
            continue
        if (
            task_category == "Result Analysis"
            and relative.suffix not in OFFICIAL_DOC_SUFFIXES
            and not row.get("touched_by_reproduction")
        ):
            continue
        selected.append(row)
    return selected


def create_tree_structure(paths: list[str]) -> str:
    tree: dict[str, Any] = {}
    for raw in paths:
        current = tree
        parts = Path(raw).parts
        for part in parts[:-1]:
            current = current.setdefault(part, {})
        if parts:
            current[parts[-1]] = None

    def render(node: dict[str, Any], prefix: str = "") -> list[str]:
        lines: list[str] = []
        entries = sorted(node.items())
        for index, (name, child) in enumerate(entries):
            last = index == len(entries) - 1
            lines.append(f"{prefix}{'└── ' if last else '├── '}{name}")
            if isinstance(child, dict):
                lines.extend(render(child, prefix + ("    " if last else "│   ")))
        return lines

    return "\n".join(render(tree))


def token_count(text: str) -> int:
    if TOKEN_ENCODER is not None:
        return len(TOKEN_ENCODER.encode(text, disallowed_special=()))
    # UTF-8 bytes are a conservative upper bound for BPE token count. This
    # fallback changes transport truncation only when tiktoken is unavailable.
    return len(text.encode("utf-8"))


def truncate_tokens(text: str, max_tokens: int) -> str:
    if max_tokens <= 0:
        return ""
    if token_count(text) <= max_tokens:
        return text
    if TOKEN_ENCODER is not None:
        return TOKEN_ENCODER.decode(
            TOKEN_ENCODER.encode(text, disallowed_special=())[:max_tokens]
        )
    return text.encode("utf-8")[:max_tokens].decode("utf-8", errors="ignore")


def read_selected_files(
    snapshot: dict[str, Any], selected_paths: list[str], *, max_tokens: int
) -> tuple[list[dict[str, Any]], str]:
    root = Path(str(snapshot.get("root") or ""))
    by_path = {
        str(row.get("path") or ""): row
        for row in snapshot.get("files", [])
        if isinstance(row, dict)
    }
    rows: list[dict[str, Any]] = []
    contents: list[str] = []
    for relative in selected_paths:
        row = by_path.get(relative)
        if row is None or row.get("mode") == "120000":
            continue
        path = root / relative
        try:
            if path.is_symlink() or not path.is_file():
                continue
            try:
                with path.open(encoding="utf-8") as handle:
                    content = handle.read(OFFICIAL_FILE_READ_LIMIT)
            except UnicodeDecodeError:
                with path.open(encoding="latin1") as handle:
                    content = handle.read(OFFICIAL_FILE_READ_LIMIT)
        except OSError:
            continue
        rendered = content if content.strip() else "(FILE IS EMPTY)"
        formatted = f"<FILE:{relative}>\n{rendered}\n</FILE:{relative}>"
        used = token_count("\n\n".join(contents))
        separator_tokens = token_count("\n\n") if contents else 0
        remaining = max_tokens - used - separator_tokens
        if remaining <= 0:
            break
        formatted = truncate_tokens(formatted, remaining)
        if not formatted:
            break
        rows.append(row)
        contents.append(formatted)
        if token_count(formatted) >= remaining:
            break
    return rows, "\n\n".join(contents)


def category_available_context(
    *, category: str, paper_md: str, reproduce_log: str, context_window_tokens: int
) -> int:
    reserved = token_count(paper_md)
    if category != "Code Development":
        reserved += token_count(reproduce_log)
    return max(0, context_window_tokens - reserved - OFFICIAL_CONTEXT_BUFFER_TOKENS)


def fit_official_primary_inputs(
    paper_md: str, reproduce_log: str, *, context_window_tokens: int
) -> tuple[str, str]:
    """Port SimpleJudge's paper/log pre-truncation before per-leaf ranking."""
    reproduce_log = truncate_tokens(reproduce_log, context_window_tokens // 2)
    available = context_window_tokens - token_count(paper_md) - token_count(reproduce_log)
    if available < 0:
        reproduce_log = truncate_tokens(
            reproduce_log,
            max(0, token_count(reproduce_log) + available - 5_000),
        )
    available = context_window_tokens - token_count(paper_md) - token_count(reproduce_log)
    if available < 0:
        paper_md = truncate_tokens(
            paper_md,
            max(0, token_count(paper_md) + available - 5_000),
        )
    return paper_md, reproduce_log


def prepare_relevant_submission(
    snapshot: dict[str, Any],
    *,
    leaf: dict[str, Any],
    paper: dict[str, str],
    addendum: str,
    reproduce_log: str,
    context_window_tokens: int,
) -> dict[str, Any]:
    # Tests and internal callers may pass evidence that has already been
    # prepared. Production snapshots always carry a root and therefore always
    # go through the official file-ranking stage below.
    if not snapshot.get("root"):
        return snapshot
    category = str(leaf.get("task_category") or "Subtree")
    candidates = whitelisted_submission_files(snapshot, category)
    candidate_paths = [str(row["path"]) for row in candidates]
    tree = create_tree_structure(candidate_paths)
    available_context = category_available_context(
        category=category,
        paper_md=paper["paper_md"],
        reproduce_log=reproduce_log,
        context_window_tokens=context_window_tokens,
    )
    if token_count(tree) >= available_context:
        # Official os.walk stops descending when the current directory depth
        # reaches four, but still includes files in that directory. A file may
        # therefore have five relative path components.
        depth_limited = [path for path in candidate_paths if len(Path(path).parts) <= 5]
        tree = create_tree_structure(depth_limited)
    if token_count(tree) >= available_context:
        tree = truncate_tokens(tree, available_context)
    if not candidate_paths:
        return {
            "files": [],
            "text": "",
            "candidate_file_count": 0,
            "committed_only": bool(snapshot.get("committed_only")),
        }

    mock_selection = os.environ.get("PAPERBENCH_JUDGE_MOCK_FILE_SELECTION")
    ranking_requested_model = ""
    ranking_reported_model = ""
    if mock_selection is not None:
        response = mock_selection
    elif os.environ.get("PAPERBENCH_JUDGE_MOCK_RESPONSE"):
        response = "\n".join(candidate_paths)
    else:
        messages = [
            {"role": "system", "content": OFFICIAL_FILE_RANKING_PROMPT},
            {"role": "user", "content": f"The paper is below:\n<paper>\n{paper['paper_md']}\n</paper>"},
            {"role": "user", "content": f"If included with the paper, you will now be shown an addendum which provides clarification for the paper and how to evaluate its reproduction:\n<addendum>\n{addendum}\n</addendum>"},
            {"role": "user", "content": f"Here is the criterion that you are grading:\n<criterion>\n{leaf.get('requirements') or ''}\n</criterion>"},
            {"role": "user", "content": f"Here are the files in the submission attempt:\n\nDirectory structure:\n{tree}\n\nNow return a list of the 10 most relevant files in order of relevance (descending) to the resolution criteria, to be provided for your inspection. Your response must contain each filename separated by newlines, with each file containing the full path. Do not write anything else."},
        ]
        completion = call_llm_completion(messages)
        response = completion["content"]
        ranking_requested_model = completion["requested_model"]
        ranking_reported_model = completion["reported_model"]

    valid = set(candidate_paths)
    selected_paths: list[str] = []
    for line in response.splitlines():
        relative = line.strip().strip("`").strip().lstrip("/")
        if relative in valid and relative not in selected_paths:
            selected_paths.append(relative)
        if len(selected_paths) >= 10:
            break
    rows, text = read_selected_files(
        snapshot,
        selected_paths,
        max_tokens=max(0, available_context - OFFICIAL_RELEVANT_FILES_BUFFER_TOKENS),
    )
    return {
        "files": rows,
        "text": text,
        "candidate_file_count": len(candidate_paths),
        "selected_file_count": len(rows),
        "committed_only": bool(snapshot.get("committed_only")),
        "file_ranking_requested_model": ranking_requested_model,
        "file_ranking_reported_model": ranking_reported_model,
    }


def extract_json_object(text: str) -> dict[str, Any]:
    try:
        payload = json.loads(text)
        if isinstance(payload, dict):
            return payload
    except json.JSONDecodeError:
        pass
    fenced = re.search(r"```(?:json)?\s*(\{.*?\})\s*```", text, re.DOTALL | re.IGNORECASE)
    if fenced:
        payload = json.loads(fenced.group(1))
        if isinstance(payload, dict):
            return payload
    match = re.search(r"\{.*\}", text, re.DOTALL)
    if not match:
        raise ValueError("LLM response did not contain a JSON object")
    payload = json.loads(match.group(0))
    if not isinstance(payload, dict):
        raise ValueError("LLM response JSON is not an object")
    return payload


def paper_excerpt(paper_dir: Path) -> dict[str, str]:
    paper_md = read_text(paper_dir / "paper.md")
    addendum = read_text(paper_dir / "addendum.md")
    blacklist = read_text(paper_dir / "blacklist.txt")
    return {"paper_md": paper_md, "addendum": addendum, "blacklist": blacklist}


def reproduction_summary(reproduction_dir: Path) -> dict[str, str]:
    executed_root = reproduction_dir / "executed" / "workspace" / "submission"
    reproduce_log_path = executed_root / "reproduce.log"
    # Official BaseJudge reads reproduce.log through read_file_content(), which
    # applies the same 200 kB per-file limit before reducing the log.
    reproduce_log = read_text(reproduce_log_path)[:OFFICIAL_FILE_READ_LIMIT]
    creation_time = read_text(executed_root / "reproduce.log.creation_time").strip()
    if not creation_time and reproduce_log_path.is_file():
        try:
            creation_time = str(reproduce_log_path.stat().st_mtime)
        except OSError:
            creation_time = ""
    return {
        "exit_code": read_text(reproduction_dir / "exit_code.txt"),
        "reproduce_log": reproduce_log,
        "reproduction_started_at": creation_time,
        "file_manifest": read_text(reproduction_dir / "file_manifest.json"),
    }


def build_leaf_messages(
    *,
    paper_id: str,
    title: str,
    leaf: dict[str, Any],
    ancestor_requirements: list[str],
    paper: dict[str, str],
    judge_addendum: str,
    raw_submission: dict[str, Any],
    executed_submission: dict[str, Any],
    reproduction: dict[str, str],
    code_only: bool,
) -> list[dict[str, str]]:
    relevant = raw_submission if code_only else executed_submission
    joined_addendum = f"{paper['addendum']}\n{judge_addendum}".strip() or "(NO ADDENDUM GIVEN)"
    if leaf.get("task_category") == "Result Analysis":
        relevant_files_prompt = (
            "Here are the most relevant docs and the files touched (i.e. modified or created) during the reproduce.sh execution, concatenated:\n"
            f"<files>\n{relevant.get('text', '')}\n</files>"
        )
    else:
        relevant_files_prompt = (
            "Here are the most relevant files included in the submission attempt, concatenated:\n"
            f"<files>\n{relevant.get('text', '')}\n</files>"
        )
    preceding = "".join(f" -> {requirement}\n" for requirement in ancestor_requirements)
    criterion_prompt = f"""The full grading rubric for the paper hierarchically decomposes various aspects of the paper. To provide more context for the criterion you are currently grading, here are some of the preceding criteria (DO NOT grade this, this is just for context):
<preceding_criteria>
{preceding}
</preceding_criteria>

Now, here is the criterion that you are grading:
<criterion>
{leaf.get('requirements') or ''}
</criterion>

The criterion you are grading is of type {leaf.get('task_category')} - {TASK_CATEGORY_QUESTIONS.get(str(leaf.get('task_category') or ''), 'Does the submission satisfy this criterion?')}"""
    messages: list[dict[str, str]] = [
        {"role": "system", "content": build_judge_task_prompt(code_only)},
        {"role": "user", "content": f"The paper is below:\n{paper['paper_md']}"},
        {
            "role": "user",
            "content": "If included with the paper, you will now be shown an addendum which provides clarification for the paper and how to evaluate its reproduction:\n"
            f"<addendum>\n{joined_addendum}\n</addendum>",
        },
        {"role": "user", "content": relevant_files_prompt},
    ]
    if not code_only:
        messages.append(
            {
                "role": "user",
                "content": "Here is the `reproduce.sh` provided in the submission, if any:\n"
                f"<reproduce.sh>\n{raw_submission.get('reproduce_sh', '')}\n</reproduce.sh>",
            }
        )
        if leaf.get("task_category") != "Code Development":
            messages.append(
                {
                    "role": "user",
                    "content": "Here is the `reproduce.log` provided in the submission, if any:\n"
                    f"<reproduce.log>\n{reproduction.get('reproduce_log', '')}\n</reproduce.log>",
                }
            )
    messages.extend(
        [
            {"role": "user", "content": criterion_prompt},
            {"role": "user", "content": OFFICIAL_GRADING_PROMPT},
        ]
    )
    return messages


def build_leaf_prompt(**kwargs: Any) -> str:
    """Compatibility helper used by tests; grading preserves message roles."""
    return "\n\n".join(message["content"] for message in build_leaf_messages(**kwargs))


def isolate_leaf_response(parsed: dict[str, Any], leaf_id: str) -> dict[str, Any]:
    """Normalize direct and legacy multi-leaf JSON to one requested leaf."""
    raw = parsed.get("leaves")
    if not isinstance(raw, list):
        raw = parsed.get("items")
    if isinstance(raw, list):
        matching = [
            row
            for row in raw
            if isinstance(row, dict)
            and str(row.get("leaf_id") or row.get("id") or "") == leaf_id
        ]
        return {"leaves": matching}
    if str(parsed.get("leaf_id") or parsed.get("id") or "") == leaf_id:
        return {"leaves": [parsed]}
    mapped = parsed.get(leaf_id)
    if isinstance(mapped, dict):
        return {"leaves": [{"leaf_id": leaf_id, **mapped}]}
    if leaf_id and "score" in parsed and not (parsed.get("leaf_id") or parsed.get("id")):
        return {"leaves": [{"leaf_id": leaf_id, **parsed}]}
    return parsed


def call_llm_completion(messages: list[dict[str, str]]) -> dict[str, str]:
    api_key = env_value("JUDGE_LLM_API_KEY")
    base_url = env_value("JUDGE_LLM_BASE_URL")
    model = env_value("PAPERBENCH_JUDGE_MODEL", "HARBOR_PAPERBENCH_JUDGE_MODEL", "MODEL_NAME") or "glm-5-3"
    if not api_key:
        raise RuntimeError("JUDGE_LLM_API_KEY is required for PaperBench LLM judge")
    endpoint = (base_url.rstrip("/") if base_url else "https://api.openai.com/v1") + "/chat/completions"
    # The cluster's forward proxy cannot resolve Kubernetes service names.  Make
    # the configured judge endpoint an explicit bypass in both cases because
    # urllib gives lowercase proxy variables precedence on Unix.
    judge_host = urllib.parse.urlsplit(endpoint).hostname
    if judge_host:
        for key in ("NO_PROXY", "no_proxy"):
            entries = [item.strip() for item in os.environ.get(key, "").split(",") if item.strip()]
            if judge_host not in entries:
                entries.append(judge_host)
            os.environ[key] = ",".join(entries)
    def post(payload: dict[str, Any]) -> dict[str, str]:
        request = urllib.request.Request(
            endpoint,
            data=json.dumps(payload).encode("utf-8"),
            headers={"Authorization": f"Bearer {api_key}", "Content-Type": "application/json"},
            method="POST",
        )
        try:
            with urllib.request.urlopen(request, timeout=int(os.environ.get("PAPERBENCH_JUDGE_TIMEOUT_SEC", "600"))) as response:
                body = response.read().decode("utf-8", errors="replace")
        except urllib.error.HTTPError as exc:
            body = exc.read().decode("utf-8", errors="replace")[:2000]
            raise RuntimeError(f"LLM judge HTTP {exc.code}: {body}") from exc
        response_payload = json.loads(body)
        return {
            "content": response_payload["choices"][0]["message"].get("content") or "",
            # The request name is configuration.  The reported name is what the
            # upstream response claims it served; Harbor cannot independently
            # authenticate a model hidden behind an OpenAI-compatible router.
            "requested_model": model,
            "reported_model": str(response_payload.get("model") or ""),
            "response_id": str(response_payload.get("id") or ""),
        }

    # Do not send temperature for gpt-5.5-compatible upstreams that reject it.
    base_payload = {"model": model, "messages": messages}
    return post(base_payload)


def call_llm_text(messages: list[dict[str, str]]) -> str:
    """Compatibility wrapper for callers that only need response text."""
    return call_llm_completion(messages)["content"]


def parse_official_judge_response(response: str) -> tuple[dict[str, Any], dict[str, str]]:
    """Apply the same binary parsing stage used by official SimpleJudge."""
    parser_messages = [
        {
            "role": "system",
            "content": "You are given a response output from a judge which should contain a score and an explanation. Please parse the text into a structured object containing `valid_score` (boolean indicating whether the response contains a valid score), the `score` (either 0 or 1), and an `explanation` (a short summary of the judge's reasoning). If the response does not contain a valid score, set `valid_score` to False and set the `score` to 0.0.",
        },
        {"role": "user", "content": response},
    ]
    completion = call_llm_completion(parser_messages)
    try:
        parsed = extract_json_object(completion["content"])
    except (ValueError, json.JSONDecodeError) as exc:
        raise JudgeResponseParseError(str(exc)) from exc
    return parsed, completion


def call_llm(messages: list[dict[str, str]], *, leaf_id: str = "") -> dict[str, Any]:
    mock = os.environ.get("PAPERBENCH_JUDGE_MOCK_RESPONSE")
    if mock:
        try:
            parsed = extract_json_object(mock)
        except (ValueError, json.JSONDecodeError) as exc:
            raise JudgeResponseParseError(str(exc)) from exc
        return isolate_leaf_response(parsed, leaf_id) if leaf_id else parsed

    judge_completion = call_llm_completion(messages)
    full_response = judge_completion["content"]
    parsed, parser_completion = parse_official_judge_response(full_response)
    raw_score = parsed.get("score")
    score_is_binary = (
        not isinstance(raw_score, bool)
        and isinstance(raw_score, (int, float))
        and float(raw_score) in {0.0, 1.0}
    )
    valid_score = parsed.get("valid_score") is True and score_is_binary
    return {
        "leaves": [
            {
                "leaf_id": leaf_id,
                "score": int(float(raw_score)) if valid_score else 0,
                "rationale": str(parsed.get("explanation") or ""),
                "evidence_paths": [],
                "invalid_reason": "" if valid_score else "official judge response did not contain a valid binary score",
                "full_judge_response": full_response,
                "judge_requested_model": judge_completion["requested_model"],
                "judge_reported_model": judge_completion["reported_model"],
                "judge_response_id": judge_completion["response_id"],
                "parser_requested_model": parser_completion["requested_model"],
                "parser_reported_model": parser_completion["reported_model"],
                "parser_response_id": parser_completion["response_id"],
            }
        ]
    }


def parse_leaf_scores(parsed: dict[str, Any], leaves: list[dict[str, Any]]) -> tuple[dict[str, float], list[dict[str, Any]], int]:
    raw = parsed.get("leaves")
    if not isinstance(raw, list):
        raw = parsed.get("items")
    if not isinstance(raw, list):
        raise ValueError("judge JSON missing leaves list")
    valid_ids = {str(leaf.get("id") or "") for leaf in leaves}
    scores: dict[str, float] = {}
    details: list[dict[str, Any]] = []
    invalid_count = 0
    seen_ids: set[str] = set()
    for row in raw:
        if not isinstance(row, dict):
            invalid_count += 1
            continue
        leaf_id = str(row.get("leaf_id") or row.get("id") or "")
        if leaf_id not in valid_ids:
            invalid_count += 1
            continue
        if leaf_id in seen_ids:
            invalid_count += 1
            continue
        seen_ids.add(leaf_id)
        raw_score = row.get("score")
        reported_invalid_reason = str(row.get("invalid_reason") or "")[:1000]
        if isinstance(raw_score, bool) or not isinstance(raw_score, (int, float)) or float(raw_score) not in {0.0, 1.0}:
            score = 0.0
            invalid_count += 1
            parser_invalid_reason = "leaf score must be exactly 0 or 1"
        elif reported_invalid_reason:
            score = 0.0
            invalid_count += 1
            parser_invalid_reason = reported_invalid_reason
        else:
            score = float(raw_score)
            parser_invalid_reason = ""
        scores[leaf_id] = score
        details.append(
            {
                "leaf_id": leaf_id,
                "score": score,
                "rationale": str(row.get("rationale") or "")[:2000],
                "evidence_paths": row.get("evidence_paths") if isinstance(row.get("evidence_paths"), list) else [],
                "invalid_reason": parser_invalid_reason,
                "full_judge_response": str(row.get("full_judge_response") or ""),
                "judge_requested_model": str(row.get("judge_requested_model") or ""),
                "judge_reported_model": str(row.get("judge_reported_model") or ""),
                "judge_response_id": str(row.get("judge_response_id") or ""),
                "parser_requested_model": str(row.get("parser_requested_model") or ""),
                "parser_reported_model": str(row.get("parser_reported_model") or ""),
                "parser_response_id": str(row.get("parser_response_id") or ""),
            }
        )
    return scores, details, invalid_count


def grade_leaf_requests(
    *,
    rubric: Any,
    paper_id: str,
    title: str,
    paper: dict[str, str],
    judge_addendum: str,
    raw_submission: dict[str, Any],
    executed_submission: dict[str, Any],
    reproduction: dict[str, str],
    code_only: bool,
    max_workers: int,
    context_window_tokens: int,
    max_prior_nodes: int | None = None,
) -> tuple[dict[str, float], list[dict[str, Any]], dict[str, int]]:
    contexts = filtered_leaf_contexts(
        rubric,
        code_only=code_only,
        max_prior_nodes=max_prior_nodes,
    )
    if not contexts:
        return {}, [], {"request_count": 0, "request_success_count": 0, "parse_success_count": 0}
    if max_workers <= 0:
        raise ValueError("judge max_workers must be positive")

    def grade_one(
        index: int,
        leaf: dict[str, Any],
        ancestors: list[str],
    ) -> tuple[int, str, float, dict[str, Any], bool, bool]:
        leaf_id = str(leaf.get("id") or "")
        try:
            joined_addendum = f"{paper['addendum']}\n{judge_addendum}".strip() or "(NO ADDENDUM GIVEN)"
            evidence_snapshot = raw_submission if code_only else executed_submission
            if leaf.get("task_category") == "Result Analysis" and not any(
                row.get("touched_by_reproduction")
                for row in whitelisted_submission_files(
                    evidence_snapshot, "Result Analysis"
                )
            ):
                detail = {
                    "leaf_id": leaf_id,
                    "score": 0.0,
                    "rationale": "Reproduce.sh did not touch any files, so there are no reproduced results to analyze.",
                    "evidence_paths": [],
                    "invalid_reason": "",
                    "full_judge_response": "",
                    "judge_available": True,
                    "llm_parse_ok": True,
                    "candidate_file_count": 0,
                    "selected_submission_files": [],
                }
                return index, leaf_id, 0.0, detail, True, True
            relevant_submission = prepare_relevant_submission(
                evidence_snapshot,
                leaf=leaf,
                paper=paper,
                addendum=joined_addendum,
                reproduce_log=reproduction.get("reproduce_log", ""),
                context_window_tokens=context_window_tokens,
            )
            prompt_raw_submission = dict(raw_submission)
            prompt_raw_submission["reproduce_sh"] = read_text(
                Path(str(raw_submission.get("root") or "")) / "reproduce.sh"
            ) if raw_submission.get("root") else str(raw_submission.get("reproduce_sh") or "")
            messages = build_leaf_messages(
                paper_id=paper_id,
                title=title,
                leaf=leaf,
                ancestor_requirements=ancestors,
                paper=paper,
                judge_addendum=judge_addendum,
                raw_submission=(relevant_submission if code_only else prompt_raw_submission),
                executed_submission=(executed_submission if code_only else relevant_submission),
                reproduction=reproduction,
                code_only=code_only,
            )
            try:
                parsed = isolate_leaf_response(call_llm(messages, leaf_id=leaf_id), leaf_id)
                scores, details, invalid_count = parse_leaf_scores(parsed, [leaf])
            except (JudgeResponseParseError, ValueError) as exc:
                detail = {
                    "leaf_id": leaf_id,
                    "score": 0.0,
                    "rationale": "",
                    "evidence_paths": [],
                    "invalid_reason": f"{type(exc).__name__}: {exc}"[:1000],
                    "judge_available": True,
                    "llm_parse_ok": False,
                    "candidate_file_count": relevant_submission.get(
                        "candidate_file_count", 0
                    ),
                    "selected_submission_files": [
                        row.get("path")
                        for row in relevant_submission.get("files", [])
                        if isinstance(row, dict)
                    ],
                }
                return index, leaf_id, 0.0, detail, True, False
            missing = leaf_id not in scores
            parse_ok = invalid_count == 0 and not missing
            detail = details[0] if details else {
                "leaf_id": leaf_id,
                "score": 0.0,
                "rationale": "",
                "evidence_paths": [],
                "invalid_reason": "judge response omitted the requested leaf",
            }
            detail["judge_available"] = True
            detail["llm_parse_ok"] = parse_ok
            detail["candidate_file_count"] = relevant_submission.get("candidate_file_count", 0)
            detail["selected_submission_files"] = [
                row.get("path")
                for row in relevant_submission.get("files", [])
                if isinstance(row, dict)
            ]
            detail["file_ranking_requested_model"] = relevant_submission.get(
                "file_ranking_requested_model", ""
            )
            detail["file_ranking_reported_model"] = relevant_submission.get(
                "file_ranking_reported_model", ""
            )
            return index, leaf_id, scores.get(leaf_id, 0.0), detail, True, parse_ok
        except Exception as exc:
            detail = {
                "leaf_id": leaf_id,
                "score": 0.0,
                "rationale": "",
                "evidence_paths": [],
                "invalid_reason": f"{type(exc).__name__}: {exc}"[:1000],
                "judge_available": False,
                "llm_parse_ok": False,
            }
            return index, leaf_id, 0.0, detail, False, False

    completed = []
    worker_count = min(max_workers, len(contexts))
    with ThreadPoolExecutor(max_workers=worker_count) as executor:
        futures = [
            executor.submit(grade_one, index, leaf, ancestors)
            for index, (leaf, ancestors) in enumerate(contexts)
        ]
        for future in as_completed(futures):
            completed.append(future.result())
    completed.sort(key=lambda row: row[0])
    scores = {leaf_id: score for _, leaf_id, score, _, _, _ in completed}
    details = [detail for _, _, _, detail, _, _ in completed]
    summary = {
        "request_count": len(completed),
        "request_success_count": sum(1 for *_, available, _ in completed if available),
        "parse_success_count": sum(1 for *_, parse_ok in completed if parse_ok),
        "max_workers": worker_count,
    }
    return scores, details, summary


def grade(args: argparse.Namespace) -> int:
    rubric = read_json(args.rubric)
    try:
        config = read_json(args.judge_config)
    except Exception:
        config = {}
    code_only = bool(args.code_only or config.get("code_only"))
    leaves = filtered_leaves(rubric, code_only=code_only)
    total_weight = sum(weight_of(leaf) for leaf in leaves)
    reproduction_ran = clipped(args.reproduction_ran)
    reproduction_success = clipped(args.reproduction_success)
    details_base = {
        "paper_id": "",
        "title": "",
        "code_only": code_only,
        "judge_model_requested": env_value(
            "PAPERBENCH_JUDGE_MODEL", "HARBOR_PAPERBENCH_JUDGE_MODEL", "MODEL_NAME"
        ) or "glm-5-3",
        "judge_model_identity_note": (
            "requested is configuration; per-request reported_model values are self-reported "
            "by the OpenAI-compatible upstream and are not independently authenticated"
        ),
        "leaf_count": len(leaves),
        "rubric_weight_total": total_weight,
        "reproduction_ran": reproduction_ran,
        "reproduction_success": reproduction_success,
    }
    try:
        details_base["paper_id"] = str(config.get("paper_id") or "")
        details_base["title"] = str(config.get("title") or "")
    except Exception:
        pass
    try:
        monitor_result = read_json(args.monitor_result)
        if not isinstance(monitor_result, dict):
            raise ValueError("monitor result is not an object")
    except Exception as exc:
        monitor_result = {
            "flagged": False,
            "monitor_error": f"{type(exc).__name__}: {exc}",
        }
    details_base["monitor"] = monitor_result
    if monitor_result.get("flagged"):
        reward = numeric_reward(
            score=0.0,
            format_score=0.0,
            submission_present=1.0 if args.submission_validation.is_file() else 0.0,
            judge_available=0.0,
            llm_parse_ok=0.0,
            leaf_count=len(leaves),
            invalid_leaf_count=0,
            rubric_weight_total=total_weight,
            reproduction_ran=0.0,
            reproduction_success=0.0,
            code_only=code_only,
        )
        write_json(args.reward_json, reward)
        write_json(
            args.details_json,
            {
                **details_base,
                "ok": True,
                "reason": "submission disqualified by PaperBench blacklist monitor",
                "leaves": [],
            },
        )
        return 0
    submission_validation: dict[str, Any] = {}
    try:
        submission_validation = read_json(args.submission_validation)
    except Exception as exc:
        submission_validation = {
            "submission_valid": False,
            "validation_error": f"{type(exc).__name__}: {exc}",
        }
    details_base["submission_validation"] = submission_validation
    if not submission_validation.get("submission_valid"):
        submission_present = 1.0 if submission_validation.get("submission_dir_exists") else 0.0
        reward = numeric_reward(
            score=0.0,
            format_score=0.0,
            submission_present=submission_present,
            judge_available=0.0,
            llm_parse_ok=0.0,
            leaf_count=len(leaves),
            invalid_leaf_count=len(leaves),
            rubric_weight_total=total_weight,
            reproduction_ran=reproduction_ran,
            reproduction_success=reproduction_success,
            code_only=code_only,
        )
        write_json(args.reward_json, reward)
        write_json(
            args.details_json,
            {
                **details_base,
                "ok": True,
                "reason": "submission failed Git repository validation",
                "leaves": [],
            },
        )
        return 0
    if not args.submission_dir.is_dir():
        reward = numeric_reward(
            score=0.0,
            format_score=0.0,
            submission_present=0.0,
            judge_available=0.0,
            llm_parse_ok=0.0,
            leaf_count=len(leaves),
            invalid_leaf_count=len(leaves),
            rubric_weight_total=total_weight,
            reproduction_ran=reproduction_ran,
            reproduction_success=reproduction_success,
            code_only=code_only,
        )
        write_json(args.reward_json, reward)
        write_json(
            args.details_json,
            {**details_base, "ok": True, "reason": "missing cleaned submission directory", "leaves": []},
        )
        return 0
    readme = args.submission_dir / "README.md"
    reproduce = args.submission_dir / "reproduce.sh"
    format_score = 1.0 if readme.is_file() and reproduce.is_file() else 0.25
    # The verifier has already applied the official `git clean -fd` contract.
    # Code-Dev evidence is enumerated from Git HEAD so ignored/untracked files
    # cannot consume the official file-ranking context. Regular mode inspects
    # the post-reproduction tree, as official SimpleJudge does.
    repro = reproduction_summary(args.reproduction_dir)
    try:
        reproduction_started_at = float(repro.get("reproduction_started_at") or "")
    except (TypeError, ValueError):
        reproduction_started_at = None
    raw_submission = collect_submission(args.submission_dir, committed_only=True)
    executed_submission = (
        raw_submission
        if code_only
        else collect_submission(
            args.executed_submission_dir,
            committed_only=False,
            reproduction_started_at=reproduction_started_at,
        )
    )
    paper = paper_excerpt(args.paper_dir)
    judge_addendum = read_text(args.judge_addendum)
    try:
        context_window_tokens = int(
            os.environ.get(
                "PAPERBENCH_JUDGE_CONTEXT_WINDOW_TOKENS",
                str(config.get("context_window_tokens") or "400000"),
            )
        )
        if context_window_tokens <= OFFICIAL_CONTEXT_BUFFER_TOKENS:
            raise ValueError("judge context window must exceed the official 10000-token buffer")
        paper["paper_md"], repro["reproduce_log"] = fit_official_primary_inputs(
            paper["paper_md"],
            repro.get("reproduce_log", ""),
            context_window_tokens=context_window_tokens,
        )
        configured_workers = os.environ.get(
            "PAPERBENCH_JUDGE_MAX_WORKERS",
            str(config.get("max_workers") or "100"),
        )
        max_workers = int(configured_workers)
        configured_max_prior_nodes = config.get("max_prior_nodes")
        max_prior_nodes = (
            int(configured_max_prior_nodes)
            if configured_max_prior_nodes is not None
            else None
        )
        if max_prior_nodes is not None and max_prior_nodes <= 0:
            raise ValueError("max_prior_nodes must be positive when configured")
        scores, leaf_details, judge_summary = grade_leaf_requests(
            rubric=rubric,
            paper_id=str(config.get("paper_id") or ""),
            title=str(config.get("title") or ""),
            paper=paper,
            judge_addendum=judge_addendum,
            raw_submission=raw_submission,
            executed_submission=executed_submission,
            reproduction=repro,
            code_only=code_only,
            max_workers=max_workers,
            context_window_tokens=context_window_tokens,
            max_prior_nodes=max_prior_nodes,
        )
        request_count = judge_summary["request_count"]
        request_success_count = judge_summary["request_success_count"]
        parse_success_count = judge_summary["parse_success_count"]
        invalid_count = request_count - parse_success_count
        weighted = score_rubric_tree(rubric, scores, code_only=code_only)
        score = clipped(weighted if weighted is not None else 0.0)
        reward = numeric_reward(
            score=score,
            format_score=format_score,
            submission_present=1.0,
            judge_available=(request_success_count / request_count if request_count else 0.0),
            llm_parse_ok=(parse_success_count / request_count if request_count else 0.0),
            leaf_count=len(leaves),
            invalid_leaf_count=invalid_count,
            rubric_weight_total=total_weight,
            reproduction_ran=reproduction_ran,
            reproduction_success=reproduction_success,
            code_only=code_only,
        )
        write_json(args.reward_json, reward)
        write_json(
            args.details_json,
            {
                **details_base,
                "ok": request_success_count > 0,
                "score": score,
                "format_score": format_score,
                "judge": {"mode": "per_leaf", **judge_summary},
                "leaves": leaf_details,
                "submission_files": raw_submission.get("files", []),
                "executed_submission_files": executed_submission.get("files", []),
                "reproduction": repro,
            },
        )
    except Exception as exc:
        reward = numeric_reward(
            score=0.0,
            format_score=format_score,
            submission_present=1.0,
            judge_available=0.0,
            llm_parse_ok=0.0,
            leaf_count=len(leaves),
            invalid_leaf_count=len(leaves),
            rubric_weight_total=total_weight,
            reproduction_ran=reproduction_ran,
            reproduction_success=reproduction_success,
            code_only=code_only,
        )
        write_json(args.reward_json, reward)
        write_json(args.details_json, {**details_base, "ok": False, "error": f"{type(exc).__name__}: {exc}"})
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description="Grade a PaperBench-style Harbor submission with an LLM rubric judge.")
    parser.add_argument("--submission-dir", type=Path, required=True)
    parser.add_argument("--executed-submission-dir", type=Path, required=True)
    parser.add_argument("--paper-dir", type=Path, required=True)
    parser.add_argument("--rubric", type=Path, required=True)
    parser.add_argument("--judge-addendum", type=Path, required=True)
    parser.add_argument("--judge-config", type=Path, required=True)
    parser.add_argument("--submission-validation", type=Path, required=True)
    parser.add_argument("--monitor-result", type=Path, required=True)
    parser.add_argument("--reproduction-dir", type=Path, required=True)
    parser.add_argument("--reproduction-ran", required=True)
    parser.add_argument("--reproduction-success", required=True)
    parser.add_argument("--reward-json", type=Path, required=True)
    parser.add_argument("--details-json", type=Path, required=True)
    parser.add_argument("--code-only", action="store_true")
    args = parser.parse_args()
    return grade(args)


if __name__ == "__main__":
    raise SystemExit(main())
